@echo off
del "%~dp0\tempres1.wav"
del "%~dp0\tempres2.opus"
del "%~dp0\tempres3.wav"
del "%~dp0\tempres4.mp3"
del "%~dp0\tempres5.opus"
del "%~dp0\tempres6.wav"
ffmpeg -i "%~s1" -c:a pcm_alaw -ar 8000 -ac 1 "%~dp0\tempres1.wav"
ffmpeg -i "%~dp0\tempres1.wav" -c:a libopus -b:a 8k -compression_level 5 -application "voip" "%~dp0\tempres2.opus"
opusdec --packet-loss 1 "%~dp0\tempres2.opus" "%~dp0\tempres3.wav"
ffmpeg -i "%~dp0\tempres3.wav" -c:a libmp3lame -b:a 8k "%~dp0\tempres4.mp3"
ffmpeg -i "%~dp0\tempres4.mp3" -c:a libopus -b:a 8k -compression_level 8 -application "voip" "%~dp0\tempres5.opus"
opusdec --packet-loss 1 "%~dp0\tempres5.opus" "%~dp0\tempres6.wav"
ffmpeg -i "%~dp0\tempres6.wav" -c:a libmp3lame -ar 44100 -q:a 5 "%~dp0\%~nx1.mp3"
